### ISSUE TITLE
500 Internal Server Error:cib/live/agents/ocf%253Aheartbeat%253Aapache

### ISSUE THREAD

**Issue by kriaos** [ClusterLabs/hawk#247]
Hawk Version : 2.6.15
OS：ubuntu

**Appearance:**
when "Create Primitive " in Web GUI ，obtain error message in web page : ****Failed to fetch meta attributes****

** Trace to :**
Request :  GET | https://192.168.197.129:7630/cib/live/agents/ocf%253Aheartbeat%253Aapache?format=json
Response: 500  Internal Server Error

**OS Messages about hawk service :**

3月 30 19:37:27 ubuntu puma[777]: 2021-03-30 19:37:27 +0800: Rack app error handling request { GET /cib/live/agents/ocf%253Aheartbeat%253Aapache }
3月 30 19:37:27 ubuntu puma[777]: #<ActionController::RoutingError: Error: Record not found>
3月 30 19:37:27 ubuntu puma[777]: /usr/share/hawk/app/controllers/application_controller.rb:206:in `not_found'
3月 30 19:37:27 ubuntu puma[777]: /usr/share/hawk/app/controllers/agents_controller.rb:38:in `block (2 levels) in show'
3月 30 19:37:27 ubuntu puma[777]: /var/lib/gems/2.3.0/gems/actionpack-5.2.4.5/lib/action_controller/metal/mime_responds.rb:203:in `respond_to'
3月 30 19:37:27 ubuntu puma[777]: /usr/share/hawk/app/controllers/agents_controller.rb:37:in `show'
3月 30 19:37:27 ubuntu puma[777]: /var/lib/gems/2.3.0/gems/actionpack-5.2.4.5/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
3月 30 19:37:27 ubuntu puma[777]: /var/lib/gems/2.3.0/gems/actionpack-5.2.4.5/lib/abstract_controller/base.rb:194:in `process_action'
3月 30 19:37:27 ubuntu puma[777]: /var/lib/gems/2.3.0/gems/actionpack-5.2.4.5/lib/action_controller/metal/rendering.rb:30:in `process_action'

Why? thanks

**Comment by wengjibo** [comment]
This is because of a problem with your ruby version. I have already successfully run hawk-2.6.15 on ubuntu 22.04 amd64. 
My OS version information and ruby version information are as follows:
root@tot-test:~# cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
root@tot-test:~# uname -m
x86_64
root@tot-test:~# ruby --version
ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [x86_64-linux]
     By the way, there are several ruby module versions as follows:
gem install sprockets:3.7.0
gem install uglifier:3.0.0
gem install puma:4.3.5
gem install js-routes:1.3.3
gem install fast_gettext:1.4.0
