### ISSUE TITLE
Hawk：Rack app error handling request { GET /roboto-v15-latin-regular.woff }

### ISSUE THREAD

**Issue by kriaos** [ClusterLabs/hawk#248]
Hawk Version : 2.6.15
OS：ubuntu

**OS error Messages periodicity about hawk service  by "journalctl -xf" :**

3月 30 22:13:03 ubuntu puma[777]: 2021-03-30 22:13:03 +0800: Rack app error handling request { GET /roboto-v15-latin-regular.woff }
3月 30 22:13:03 ubuntu puma[777]: #<Errno::EACCES: Permission denied @ utime_internal - /usr/share/hawk/tmp/cache/assets/sprockets/v3.0/oR/oRRLppPQiVBIkytrZdGaoQR5Ua0aEDmLHC7DaxpxWKs.cache>
3月 30 22:13:03 ubuntu puma[777]: /usr/lib/ruby/2.3.0/fileutils.rb:1154:in `utime'
3月 30 22:13:03 ubuntu puma[777]: /usr/lib/ruby/2.3.0/fileutils.rb:1154:in `block in touch'
3月 30 22:13:03 ubuntu puma[777]: /usr/lib/ruby/2.3.0/fileutils.rb:1151:in `each'
3月 30 22:13:03 ubuntu puma[777]: /usr/lib/ruby/2.3.0/fileutils.rb:1151:in `touch'
3月 30 22:13:03 ubuntu puma[777]: /var/lib/gems/2.3.0/gems/sprockets-3.7.2/lib/sprockets/cache/file_store.rb:67:in `get'
3月 30 22:13:03 ubuntu puma[777]: /var/lib/gems/2.3.0/gems/sprockets-3.7.2/lib/sprockets/cache.rb:208:in `get'
3月 30 22:13:03 ubuntu puma[777]: /var/lib/gems/2.3.0/gems/sprockets-3.7.2/lib/sprockets/cache.rb:83:in `fetch'
3月 30 22:13:03 ubuntu puma[777]: /var/lib/gems/2.3.0/gems/sprockets-3.7.2/lib/sprockets/base.rb:56:in `file_digest'
3月 30 22:13:03 ubuntu puma[777]: /var/lib/gems/2.3.0/gems/sprockets-3.7.2/lib/sprockets/unloaded_asset.rb:104:in `dependency_history_key'
3月 30 22:13:03 ubuntu puma[777]: /var/lib/gems/2.3.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:304:in `fetch_asset_from_dependency_cache'

How to solve it ? thnks

**Comment by kriaos** [comment]
chmod -R 777 /usr/share/hawk
